version: '3.1'

services:

  db:
    image: postgres:13.2-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: payment
      POSTGRES_PASSWORD: supersecret

  adminer:
    image: adminer
    restart: always
    ports:
      - 80:8080
